id: PE542AF4D
initial_creation_type: input
source_metadata:
  Title: Śabdabhedaprakāśaḥ
  Editor: Śabdabhedaprakāśaḥ
  Publisher: '-'
  Place of Publication: '-'
  Year: '-'
  Śabdabhedaprakāśaḥ:
    Text Version: Romanized
    Input Personnel: Bibek Shakya
    Input Date: '2018'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:14:09.862499'
last_modified_at: '2022-03-08T17:14:09.862508'
